<a href="https://colab.research.google.com/github/superkisa/MaGaML/blob/main/MathRefresher/sem_Gram-Schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Gram-Schmidt Process**

In this notebook, you'll implement the Gram-Schmidt process.

## **NumPy: the very basics**

We'll start with reviewing (or getting familiar with) some useful functions from the $\texttt{numpy}$ library that is used for vector computations in Python.

Let's import it first:

In [1]:
import numpy as np

Here are some useful commands:

In [ ]:
# Creating a vector
np.array([1, 1, 2])

array([1, 1, 2])

In [ ]:
# Computing dot product
np.dot(np.array([1.,1.,1.]), np.array([1.,0.,1.]))

2.0

In [ ]:
# Computig length of a vector (default - l2)
np.linalg.norm(np.array([1, 1, 2]))

2.449489742783178

Remember how else can we compute the same vector length using just the dot product? Try it out!

Hint: $||x||_2 = \sqrt{(x,x)}$.

In [3]:
# Your code here
import math
math.sqrt(np.sum((np.array([1, 1, 2]))**2))

2.449489742783178

## **Implementing Gram-Schmidt Process**

During the exercise session, we dicscussed the so-called **Gram-Schmidt pocess** that allows one to transform any basis of a linear subspace into an orthogonal one, i.e., into a basis where vectors are mutually orthogonal.

Let's recall how this procedure goes.

Imagine you have a basis $B = \{b_1, b_2, ..., b_n\}$. Let's construct an orthogonal basis $V = \{v_1, v_2, ..., v_n\}$ from it.

1. Set $v_1 = b_1$.

2. Let's look for $v_2$ as $v_2 = b_2 + \alpha v_1$, where $\alpha$ is a number that we chose in such a way that the vectors $v_1$ and $v_2$ are indeed orthogonal:

$0 = (v_1, v_2) = (v_1, b_2 + \alpha v_1) = (v_1, b_2) = \alpha(v_1, v_1)$. 

So, $\alpha = - \frac{(v_1, b_2)}{(v_1, v_1)}$ and we can compute $v_2$ as  $v_2 = b_2 + - \frac{(v_1, b_2)}{(v_1, v_1)} v_1$.

3. Imagine that we've already constructed vectors $v_1, ..., v_{k-1}$ in our orthogonal basis. We are now looking for vector $v_k = b_k + \alpha_1 v_1 + \alpha_2 v_2 + ... + \alpha_{k-1} v_{k-1}$.

Again, we chose numbers $\alpha_1, ..., \alpha_{k-1}$ in such a way that $(v_k, v_i) = 0 \ \forall i = 1, ..., k-1$:

$0 = (v_k, v_i) = (v_k, b_k) + \alpha_1 (v_k, v_1) + ... + \alpha_i (v_i, v_i) + ... +\alpha_{k-1}(v_k, v_{k-1}) = (v_k, b_k) + $

That means that $\alpha_i = - \frac{(v_i, b_k)}{(v_i, v_i)}$ and

$v_k = b_k + - \frac{(v_1, b_k)}{(v_1, v_1)} v_1 + - \frac{(v_2, b_k)}{(v_2, v_2)} v_2 + ... + - \frac{(v_{k-1}, b_k)}{(v_{k-1}, v_{k-1})} v_{k-1}$.



Your task is to implement a function that takes a list of basis vectors ($\texttt{numpy}$-arrays) and constructs an orthogonal basis from it following the Gram-Schmidt process described above.

In [23]:
def gram_schmidt(basis, normalize=False):
  # Your code here
  v1 = basis[0]
  alpha = - np.dot(v1, basis[1]) / np.dot(v1, v1)
  v2 = basis[1] + alpha*v1
  alpha1 = - np.dot(v1, basis[2]) / np.dot(v1, v1)
  alpha2 = - np.dot(v2, basis[2]) / np.dot(v2, v2)
  v3 = basis[2] + alpha1*v1 + alpha2*v2
  if normalize == True:
      v1 = v1 / np.linalg.norm(v1)
      v2 = v2 / np.linalg.norm(v2)
      v3 = v3 / np.linalg.norm(v3)
  return [v1, v2, v3]

In [24]:
basis1 = [np.array([1.,1.,1.]), 
         np.array([1.,1.,2.]), 
         np.array([1.,2.,3.])]

gram_schmidt(basis1)

[array([1., 1., 1.]),
 array([-0.33333333, -0.33333333,  0.66666667]),
 array([-5.0000000e-01,  5.0000000e-01, -4.4408921e-16])]

Let's try to orthogonalize some basis with the help of your new function! Check that everything works as expected.

In [25]:
basis2 = [np.array([1.,1.,1.]), 
         np.array([1.,2.,0.]), 
         np.array([2.,0.,1.])]

gram_schmidt(basis2, normalize=True)

[array([0.57735027, 0.57735027, 0.57735027]),
 array([ 0.        ,  0.70710678, -0.70710678]),
 array([ 0.81649658, -0.40824829, -0.40824829])]

Another example:

In [26]:
v = gram_schmidt(basis2)
v

[array([1., 1., 1.]), array([ 0.,  1., -1.]), array([ 1. , -0.5, -0.5])]

Now, change the orthogonalization process so that you get not just orthogonal but orthonormal basis. 

Then, run the examples again to check it out.